language: node_js
cache:
  directories:
    - ~/.npm
install: npm install
jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm run build:prod
        - npm run lint
        - npm run test
        - npm run is-es5
      - after_success:
        - npm run codecov
    - stage: deploy
      if: branch = master
      script:
        - npm run deploy
